# simple dockerfile to test OCP s2i using Dockerfile 

FROM registry.access.redhat.com/ubi7:latest

# se cambio parametro del documento para la siguiente prueba
CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
